import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <nav className="px-2 py-2 border-b top-0 z-50 bg-background w-full">
            <Navbar />
          </nav>
          <div className="">{children}</div>
          <Toaster duration={2000} />
        </Providers>
      </body>
    </html>
  );
}
